version: "3"
services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: todolist
      DB_USER: user
      DB_PASSWORD: password

  postgres-db:
    container_name: todolist-db
    image: postgres:15.2-alpine
    command: -c log_statement=all
    ports:
      - 5432:5432
    environment:
      POSTGRES_SERVER: db
      POSTGRES_DB: todolist
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
    volumes:
      - db-volume:/var/lib/postgresql/data
  auth-redis:
    container_name: auth-redis
    image: redis:7.2-alpine
    ports:
      - 6379:6379

volumes:
  db-volume:
